apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: celery-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hotwings.3cv-research.com
    http:
      paths:
      - path: /
        backend:
          serviceName: celery-gateway
          servicePort: 80
